// Fun colorful icons for categories
export const categoryIcons = [
  { name: 'restaurant', color: '#FF6B6B', label: 'Restaurant' },
  { name: 'shopping_cart', color: '#4ECDC4', label: 'Shopping' },
  { name: 'local_gas_station', color: '#FFE66D', label: 'Gas' },
  { name: 'home', color: '#95E1D3', label: 'Home' },
  { name: 'flight', color: '#F38181', label: 'Travel' },
  { name: 'fitness_center', color: '#AA96DA', label: 'Fitness' },
  { name: 'local_hospital', color: '#FCBAD3', label: 'Health' },
  { name: 'school', color: '#A8E6CF', label: 'Education' },
  { name: 'movie', color: '#FFD3A5', label: 'Entertainment' },
  { name: 'directions_car', color: '#FF8B94', label: 'Transport' },
  { name: 'pets', color: '#C7CEEA', label: 'Pets' },
  { name: 'shopping_bag', color: '#FFB6C1', label: 'Retail' },
  { name: 'fastfood', color: '#FFD700', label: 'Fast Food' },
  { name: 'coffee', color: '#8B4513', label: 'Coffee' },
  { name: 'sports_esports', color: '#9370DB', label: 'Gaming' },
  { name: 'music_note', color: '#FF69B4', label: 'Music' },
  { name: 'beach_access', color: '#00CED1', label: 'Leisure' },
  { name: 'work', color: '#4169E1', label: 'Work' },
  { name: 'account_balance', color: '#32CD32', label: 'Banking' },
  { name: 'savings', color: '#FFD700', label: 'Savings' },
  { name: 'trending_up', color: '#00FF00', label: 'Investment' },
  { name: 'payments', color: '#FF6347', label: 'Payment' },
  { name: 'receipt', color: '#4682B4', label: 'Bills' },
  { name: 'phone', color: '#20B2AA', label: 'Phone' },
  { name: 'wifi', color: '#9370DB', label: 'Internet' },
  { name: 'electric_bolt', color: '#FFD700', label: 'Utilities' },
  { name: 'water_drop', color: '#00BFFF', label: 'Water' },
  { name: 'local_fire_department', color: '#FF4500', label: 'Heating' },
  { name: 'grocery_store', color: '#32CD32', label: 'Groceries' },
  { name: 'lunch_dining', color: '#FF69B4', label: 'Dining' },
  { name: 'local_bar', color: '#8B0000', label: 'Drinks' },
  { name: 'cake', color: '#FFB6C1', label: 'Dessert' },
  { name: 'spa', color: '#FF69B4', label: 'Beauty' },
  { name: 'cut', color: '#9370DB', label: 'Haircut' },
  { name: 'dry_cleaning', color: '#4682B4', label: 'Laundry' },
  { name: 'book', color: '#8B4513', label: 'Books' },
  { name: 'sports_soccer', color: '#228B22', label: 'Sports' },
  { name: 'theater_comedy', color: '#FF1493', label: 'Theater' },
  { name: 'celebration', color: '#FFD700', label: 'Celebration' },
  { name: 'card_giftcard', color: '#FF69B4', label: 'Gifts' },
  { name: 'favorite', color: '#FF1493', label: 'Favorites' },
  { name: 'star', color: '#FFD700', label: 'Star' },
  { name: 'diamond', color: '#00CED1', label: 'Diamond' },
  { name: 'emoji_events', color: '#FFD700', label: 'Award' },
  { name: 'attach_money', color: '#32CD32', label: 'Money' },
  { name: 'account_balance_wallet', color: '#4169E1', label: 'Wallet' },
  { name: 'credit_card', color: '#FF6347', label: 'Credit Card' },
  { name: 'savings', color: '#FFD700', label: 'Savings' },
  { name: 'wallet', color: '#9370DB', label: 'Wallet' }
]

export const categoryGroupIcons = [
  { name: 'folder', color: '#FF6B6B', label: 'Folder' },
  { name: 'category', color: '#4ECDC4', label: 'Category' },
  { name: 'dashboard', color: '#FFE66D', label: 'Dashboard' },
  { name: 'apps', color: '#95E1D3', label: 'Apps' },
  { name: 'view_module', color: '#F38181', label: 'Grid' },
  { name: 'view_list', color: '#AA96DA', label: 'List' },
  { name: 'inventory_2', color: '#FCBAD3', label: 'Inventory' },
  { name: 'collections', color: '#A8E6CF', label: 'Collections' },
  { name: 'layers', color: '#FFD3A5', label: 'Layers' },
  { name: 'widgets', color: '#FF8B94', label: 'Widgets' },
  { name: 'account_tree', color: '#C7CEEA', label: 'Tree' },
  { name: 'folder_special', color: '#FFB6C1', label: 'Special Folder' },
  { name: 'bookmark', color: '#FFD700', label: 'Bookmark' },
  { name: 'label', color: '#9370DB', label: 'Label' },
  { name: 'local_offer', color: '#FF69B4', label: 'Tag' },
  { name: 'star', color: '#FFD700', label: 'Star' },
  { name: 'favorite', color: '#FF1493', label: 'Favorite' },
  { name: 'bookmark_border', color: '#00CED1', label: 'Bookmark Border' },
  { name: 'folder_open', color: '#4169E1', label: 'Open Folder' },
  { name: 'archive', color: '#32CD32', label: 'Archive' }
]

export function getIconByName(iconName) {
  const allIcons = [...categoryIcons, ...categoryGroupIcons]
  return allIcons.find(icon => icon.name === iconName) || categoryIcons[0]
}

