// Fun colorful icons for categories
export const categoryIcons = [
  { name: 'restaurant', color: '#FF6B6B', label: 'Restaurant' },
  { name: 'shopping_cart', color: '#4ECDC4', label: 'Shopping' },
  { name: 'local_gas_station', color: '#FFE66D', label: 'Gas' },
  { name: 'home', color: '#95E1D3', label: 'Home' },
  { name: 'flight', color: '#F38181', label: 'Travel' },
  { name: 'fitness_center', color: '#AA96DA', label: 'Fitness' },
  { name: 'local_hospital', color: '#FCBAD3', label: 'Health' },
  { name: 'school', color: '#A8E6CF', label: 'Education' },
  { name: 'movie', color: '#FFD3A5', label: 'Entertainment' },
  { name: 'directions_car', color: '#FF8B94', label: 'Transport' },
  { name: 'pets', color: '#C7CEEA', label: 'Pets' },
  { name: 'shopping_bag', color: '#FFB6C1', label: 'Retail' },
  { name: 'fastfood', color: '#FFD700', label: 'Fast Food' },
  { name: 'coffee', color: '#8B4513', label: 'Coffee' },
  { name: 'sports_esports', color: '#9370DB', label: 'Gaming' },
  { name: 'music_note', color: '#FF69B4', label: 'Music' },
  { name: 'beach_access', color: '#00CED1', label: 'Leisure' },
  { name: 'work', color: '#4169E1', label: 'Work' },
  { name: 'account_balance', color: '#32CD32', label: 'Banking' },
  { name: 'savings', color: '#FFD700', label: 'Savings' },
  { name: 'trending_up', color: '#00FF00', label: 'Investment' },
  { name: 'payments', color: '#FF6347', label: 'Payment' },
  { name: 'receipt', color: '#4682B4', label: 'Bills' },
  { name: 'phone', color: '#20B2AA', label: 'Phone' },
  { name: 'wifi', color: '#9370DB', label: 'Internet' },
  { name: 'electric_bolt', color: '#FFD700', label: 'Utilities' },
  { name: 'water_drop', color: '#00BFFF', label: 'Water' },
  { name: 'local_fire_department', color: '#FF4500', label: 'Heating' },
  { name: 'grocery_store', color: '#32CD32', label: 'Groceries' },
  { name: 'lunch_dining', color: '#FF69B4', label: 'Dining' },
  { name: 'local_bar', color: '#8B0000', label: 'Drinks' },
  { name: 'cake', color: '#FFB6C1', label: 'Dessert' },
  { name: 'spa', color: '#FF69B4', label: 'Beauty' },
  { name: 'cut', color: '#9370DB', label: 'Haircut' },
  { name: 'content_cut', color: '#9370DB', label: 'Hair Care' },
  { name: 'face', color: '#FF69B4', label: 'Personal Care' },
  { name: 'dry_cleaning', color: '#4682B4', label: 'Laundry' },
  { name: 'book', color: '#8B4513', label: 'Books' },
  { name: 'sports_soccer', color: '#228B22', label: 'Sports' },
  { name: 'theater_comedy', color: '#FF1493', label: 'Theater' },
  { name: 'celebration', color: '#FFD700', label: 'Celebration' },
  { name: 'card_giftcard', color: '#FF69B4', label: 'Gifts' },
  { name: 'favorite', color: '#FF1493', label: 'Favorites' },
  { name: 'star', color: '#FFD700', label: 'Star' },
  { name: 'diamond', color: '#00CED1', label: 'Diamond' },
  { name: 'emoji_events', color: '#FFD700', label: 'Award' },
  { name: 'attach_money', color: '#32CD32', label: 'Money' },
  { name: 'account_balance_wallet', color: '#4169E1', label: 'Wallet' },
  { name: 'credit_card', color: '#FF6347', label: 'Credit Card' },
  { name: 'savings', color: '#FFD700', label: 'Savings' },
  { name: 'wallet', color: '#9370DB', label: 'Wallet' },
  { name: 'restaurant_menu', color: '#FF6B6B', label: 'Menu' },
  { name: 'local_pizza', color: '#FF8C00', label: 'Pizza' },
  { name: 'icecream', color: '#FFB6C1', label: 'Ice Cream' },
  { name: 'local_cafe', color: '#8B4513', label: 'Cafe' },
  { name: 'bakery_dining', color: '#D2691E', label: 'Bakery' },
  { name: 'ramen_dining', color: '#FF6347', label: 'Asian Food' },
  { name: 'dining', color: '#FF69B4', label: 'Fine Dining' },
  { name: 'store', color: '#4ECDC4', label: 'Store' },
  { name: 'storefront', color: '#4ECDC4', label: 'Shop' },
  { name: 'shopping_basket', color: '#FFB6C1', label: 'Basket' },
  { name: 'local_mall', color: '#9370DB', label: 'Mall' },
  { name: 'liquor', color: '#8B0000', label: 'Alcohol' },
  { name: 'wine_bar', color: '#8B0000', label: 'Wine' },
  { name: 'local_pharmacy', color: '#FCBAD3', label: 'Pharmacy' },
  { name: 'medical_services', color: '#FCBAD3', label: 'Medical' },
  { name: 'healing', color: '#FCBAD3', label: 'Wellness' },
  { name: 'vaccines', color: '#FCBAD3', label: 'Vaccines' },
  { name: 'medication', color: '#FCBAD3', label: 'Medication' },
  { name: 'hotel', color: '#F38181', label: 'Hotel' },
  { name: 'luggage', color: '#F38181', label: 'Luggage' },
  { name: 'beach_access', color: '#00CED1', label: 'Beach' },
  { name: 'pool', color: '#00CED1', label: 'Pool' },
  { name: 'sports_baseball', color: '#228B22', label: 'Baseball' },
  { name: 'sports_basketball', color: '#FF6347', label: 'Basketball' },
  { name: 'sports_football', color: '#8B4513', label: 'Football' },
  { name: 'sports_tennis', color: '#32CD32', label: 'Tennis' },
  { name: 'golf_course', color: '#228B22', label: 'Golf' },
  { name: 'fitness_center', color: '#AA96DA', label: 'Gym' },
  { name: 'self_improvement', color: '#AA96DA', label: 'Yoga' },
  { name: 'directions_bus', color: '#FF8B94', label: 'Bus' },
  { name: 'train', color: '#FF8B94', label: 'Train' },
  { name: 'subway', color: '#FF8B94', label: 'Subway' },
  { name: 'flight_takeoff', color: '#F38181', label: 'Flight' },
  { name: 'hotel', color: '#F38181', label: 'Accommodation' },
  { name: 'car_rental', color: '#FF8B94', label: 'Car Rental' },
  { name: 'parking', color: '#FFE66D', label: 'Parking' },
  { name: 'local_taxi', color: '#FFE66D', label: 'Taxi' },
  { name: 'two_wheeler', color: '#FFE66D', label: 'Motorcycle' },
  { name: 'bike_scooter', color: '#FFE66D', label: 'Scooter' },
  { name: 'laptop', color: '#9370DB', label: 'Electronics' },
  { name: 'computer', color: '#9370DB', label: 'Computer' },
  { name: 'phone_iphone', color: '#20B2AA', label: 'Mobile' },
  { name: 'tablet', color: '#9370DB', label: 'Tablet' },
  { name: 'tv', color: '#FFD3A5', label: 'TV' },
  { name: 'headphones', color: '#9370DB', label: 'Headphones' },
  { name: 'camera', color: '#9370DB', label: 'Camera' },
  { name: 'videogame_asset', color: '#9370DB', label: 'Video Games' },
  { name: 'toys', color: '#FF69B4', label: 'Toys' },
  { name: 'child_care', color: '#FF69B4', label: 'Child Care' },
  { name: 'crib', color: '#FF69B4', label: 'Baby' },
  { name: 'pets', color: '#C7CEEA', label: 'Pet' },
  { name: 'cruelty_free', color: '#C7CEEA', label: 'Pet Care' },
  { name: 'cleaning_services', color: '#4682B4', label: 'Cleaning' },
  { name: 'home_repair_service', color: '#95E1D3', label: 'Home Repair' },
  { name: 'plumbing', color: '#00BFFF', label: 'Plumbing' },
  { name: 'construction', color: '#FF8C00', label: 'Construction' },
  { name: 'paint', color: '#FFD700', label: 'Paint' },
  { name: 'lightbulb', color: '#FFD700', label: 'Lighting' },
  { name: 'security', color: '#4682B4', label: 'Security' },
  { name: 'lock', color: '#4682B4', label: 'Lock' },
  { name: 'school', color: '#A8E6CF', label: 'School' },
  { name: 'menu_book', color: '#8B4513', label: 'Textbook' },
  { name: 'library_books', color: '#8B4513', label: 'Library' },
  { name: 'palette', color: '#FF69B4', label: 'Art' },
  { name: 'brush', color: '#FF69B4', label: 'Art Supplies' },
  { name: 'theater_comedy', color: '#FF1493', label: 'Comedy' },
  { name: 'music_note', color: '#FF69B4', label: 'Music' },
  { name: 'library_music', color: '#FF69B4', label: 'Music Library' },
  { name: 'mic', color: '#FF69B4', label: 'Microphone' },
  { name: 'movie', color: '#FFD3A5', label: 'Movie' },
  { name: 'movie_filter', color: '#FFD3A5', label: 'Cinema' },
  { name: 'sports_esports', color: '#9370DB', label: 'Gaming' },
  { name: 'casino', color: '#9370DB', label: 'Casino' },
  { name: 'sports_bar', color: '#8B0000', label: 'Sports Bar' },
  { name: 'nightlife', color: '#8B0000', label: 'Nightlife' },
  { name: 'local_activity', color: '#FF1493', label: 'Activity' },
  { name: 'festival', color: '#FFD700', label: 'Festival' },
  { name: 'celebration', color: '#FFD700', label: 'Party' },
  { name: 'cake', color: '#FFB6C1', label: 'Birthday' },
  { name: 'card_giftcard', color: '#FF69B4', label: 'Gift' },
  { name: 'redeem', color: '#FF69B4', label: 'Reward' },
  { name: 'volunteer_activism', color: '#FF1493', label: 'Donation' },
  { name: 'favorite', color: '#FF1493', label: 'Charity' },
  { name: 'church', color: '#9370DB', label: 'Church' },
  { name: 'mosque', color: '#9370DB', label: 'Mosque' },
  { name: 'temple_buddhist', color: '#9370DB', label: 'Temple' },
  { name: 'account_balance', color: '#32CD32', label: 'Bank' },
  { name: 'account_balance_wallet', color: '#4169E1', label: 'Wallet' },
  { name: 'savings', color: '#FFD700', label: 'Savings' },
  { name: 'trending_up', color: '#00FF00', label: 'Investment' },
  { name: 'show_chart', color: '#00FF00', label: 'Stocks' },
  { name: 'pie_chart', color: '#00FF00', label: 'Portfolio' },
  { name: 'payments', color: '#FF6347', label: 'Payment' },
  { name: 'credit_card', color: '#FF6347', label: 'Card' },
  { name: 'receipt_long', color: '#4682B4', label: 'Receipt' },
  { name: 'description', color: '#4682B4', label: 'Document' },
  { name: 'insurance', color: '#4682B4', label: 'Insurance' },
  { name: 'health_and_safety', color: '#FCBAD3', label: 'Health Insurance' },
  { name: 'car_crash', color: '#FF6347', label: 'Auto Insurance' },
  { name: 'home', color: '#95E1D3', label: 'Home Insurance' },
  { name: 'subscriptions', color: '#9370DB', label: 'Subscription' },
  { name: 'stream', color: '#9370DB', label: 'Streaming' },
  { name: 'movie', color: '#FFD3A5', label: 'Video Streaming' },
  { name: 'music_note', color: '#FF69B4', label: 'Music Streaming' },
  { name: 'podcasts', color: '#9370DB', label: 'Podcast' },
  { name: 'newspaper', color: '#4682B4', label: 'News' },
  { name: 'magazine', color: '#4682B4', label: 'Magazine' },
  { name: 'cloud', color: '#00BFFF', label: 'Cloud Storage' },
  { name: 'storage', color: '#00BFFF', label: 'Storage' },
  { name: 'apps', color: '#95E1D3', label: 'App' },
  { name: 'gamepad', color: '#9370DB', label: 'Gaming App' },
  { name: 'phone', color: '#20B2AA', label: 'Phone Service' },
  { name: 'wifi', color: '#9370DB', label: 'Internet' },
  { name: 'router', color: '#9370DB', label: 'Router' },
  { name: 'cable', color: '#9370DB', label: 'Cable' },
  { name: 'satellite', color: '#9370DB', label: 'Satellite' },
  { name: 'electric_bolt', color: '#FFD700', label: 'Electricity' },
  { name: 'water_drop', color: '#00BFFF', label: 'Water' },
  { name: 'local_fire_department', color: '#FF4500', label: 'Gas/Heating' },
  { name: 'propane_tank', color: '#FF4500', label: 'Propane' },
  { name: 'snowflake', color: '#00BFFF', label: 'AC' },
  { name: 'ac_unit', color: '#00BFFF', label: 'Air Conditioning' },
  { name: 'yard', color: '#32CD32', label: 'Yard' },
  { name: 'grass', color: '#32CD32', label: 'Lawn' },
  { name: 'local_florist', color: '#FF69B4', label: 'Florist' },
  { name: 'park', color: '#32CD32', label: 'Park' },
  { name: 'camping', color: '#8B4513', label: 'Camping' },
  { name: 'hiking', color: '#228B22', label: 'Hiking' },
  { name: 'snowboarding', color: '#00BFFF', label: 'Snowboarding' },
  { name: 'skateboarding', color: '#FF6347', label: 'Skateboarding' },
  { name: 'sailing', color: '#00CED1', label: 'Sailing' },
  { name: 'kayaking', color: '#00CED1', label: 'Kayaking' },
  { name: 'fishing', color: '#00CED1', label: 'Fishing' },
  { name: 'golf_course', color: '#228B22', label: 'Golf Course' },
  { name: 'sports_mma', color: '#FF6347', label: 'Martial Arts' },
  { name: 'sports_martial_arts', color: '#FF6347', label: 'Karate' },
  { name: 'pool', color: '#00CED1', label: 'Swimming' },
  { name: 'rowing', color: '#00CED1', label: 'Rowing' },
  { name: 'directions_run', color: '#FF6347', label: 'Running' },
  { name: 'directions_walk', color: '#228B22', label: 'Walking' },
  { name: 'directions_bike', color: '#228B22', label: 'Cycling' },
  { name: 'skateboarding', color: '#FF6347', label: 'Skating' },
  { name: 'snowshoeing', color: '#00BFFF', label: 'Snowshoeing' },
  { name: 'downhill_skiing', color: '#00BFFF', label: 'Skiing' },
  { name: 'ice_skating', color: '#00BFFF', label: 'Ice Skating' },
  { name: 'sports_handball', color: '#FF6347', label: 'Handball' },
  { name: 'sports_volleyball', color: '#FF6347', label: 'Volleyball' },
  { name: 'sports_cricket', color: '#228B22', label: 'Cricket' },
  { name: 'sports_hockey', color: '#00BFFF', label: 'Hockey' },
  { name: 'sports_kabaddi', color: '#FF6347', label: 'Kabaddi' },
  { name: 'sports_motorsports', color: '#FF6347', label: 'Motorsports' },
  { name: 'sports_rugby', color: '#228B22', label: 'Rugby' },
  { name: 'sports', color: '#228B22', label: 'Sports General' },
  { name: 'sports_score', color: '#228B22', label: 'Sports Score' },
  { name: 'sports_soccer', color: '#228B22', label: 'Soccer' },
  { name: 'sports_tennis', color: '#32CD32', label: 'Tennis' },
  { name: 'sports_basketball', color: '#FF6347', label: 'Basketball' },
  { name: 'sports_baseball', color: '#228B22', label: 'Baseball' },
  { name: 'sports_football', color: '#8B4513', label: 'Football' },
  { name: 'sports_golf', color: '#228B22', label: 'Golf' },
  { name: 'sports_handball', color: '#FF6347', label: 'Handball' },
  { name: 'sports_volleyball', color: '#FF6347', label: 'Volleyball' },
  { name: 'sports_cricket', color: '#228B22', label: 'Cricket' },
  { name: 'sports_hockey', color: '#00BFFF', label: 'Hockey' },
  { name: 'sports_kabaddi', color: '#FF6347', label: 'Kabaddi' },
  { name: 'sports_motorsports', color: '#FF6347', label: 'Motorsports' },
  { name: 'sports_rugby', color: '#228B22', label: 'Rugby' },
  { name: 'sports', color: '#228B22', label: 'Sports General' },
  { name: 'sports_score', color: '#228B22', label: 'Sports Score' }
]

export const categoryGroupIcons = [
  { name: 'folder', color: '#FF6B6B', label: 'Folder' },
  { name: 'category', color: '#4ECDC4', label: 'Category' },
  { name: 'dashboard', color: '#FFE66D', label: 'Dashboard' },
  { name: 'apps', color: '#95E1D3', label: 'Apps' },
  { name: 'view_module', color: '#F38181', label: 'Grid' },
  { name: 'view_list', color: '#AA96DA', label: 'List' },
  { name: 'inventory_2', color: '#FCBAD3', label: 'Inventory' },
  { name: 'collections', color: '#A8E6CF', label: 'Collections' },
  { name: 'layers', color: '#FFD3A5', label: 'Layers' },
  { name: 'widgets', color: '#FF8B94', label: 'Widgets' },
  { name: 'account_tree', color: '#C7CEEA', label: 'Tree' },
  { name: 'folder_special', color: '#FFB6C1', label: 'Special Folder' },
  { name: 'bookmark', color: '#FFD700', label: 'Bookmark' },
  { name: 'label', color: '#9370DB', label: 'Label' },
  { name: 'local_offer', color: '#FF69B4', label: 'Tag' },
  { name: 'star', color: '#FFD700', label: 'Star' },
  { name: 'favorite', color: '#FF1493', label: 'Favorite' },
  { name: 'bookmark_border', color: '#00CED1', label: 'Bookmark Border' },
  { name: 'folder_open', color: '#4169E1', label: 'Open Folder' },
  { name: 'archive', color: '#32CD32', label: 'Archive' }
]

export function getIconByName(iconName) {
  const allIcons = [...categoryIcons, ...categoryGroupIcons]
  return allIcons.find(icon => icon.name === iconName) || categoryIcons[0]
}

